name: 'action-github-app-token'
description: 'Gets a GitHub auth token for a GitHub App installation'
author: 'sentry.io'
inputs:
  app_id:
    required: true
    description: 'GitHub App ID'
  private_key:
    required: true
    description: 'Private key for the GitHub App'
  base_url:
    required: true
    description: 'Base url for the GitHub Install'
outputs:
  token:
    description: 'Github Token for App installation'
runs:
  using: 'node12'
  main: 'dist/index.js'
